"""initial migration

Revision ID: 4aad523a7cfe
Revises: 
Create Date: 2026-07-24 00:45:28.646368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aad523a7cfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animaltype',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('name_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('breed',
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['animaltype.type_id'], ),
    sa.PrimaryKeyConstraint('breed_id')
    )
    op.create_table('animal',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('arrival_age_months', sa.Integer(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.breed_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['animal.animal_id'], ),
    sa.PrimaryKeyConstraint('animal_id')
    )
    op.create_index(op.f('ix_animal_inventory_number'), 'animal', ['inventory_number'], unique=True)
    op.create_table('weighting',
    sa.Column('weighting_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('weighting_id'),
    sa.UniqueConstraint('animal_id', 'date', name='uq_animal_weighting_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weighting')
    op.drop_index(op.f('ix_animal_inventory_number'), table_name='animal')
    op.drop_table('animal')
    op.drop_table('breed')
    op.drop_table('users')
    op.drop_table('animaltype')
    # ### end Alembic commands ###
