"""add ON DELETE SET NULL for animal parent_id

Revision ID: be26adc97774
Revises: 4aad523a7cfe
Create Date: 2026-07-25 23:13:41.563581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be26adc97774'
down_revision: Union[str, Sequence[str], None] = '4aad523a7cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('animal_parent_id_fkey', 'animal', type_='foreignkey')
    op.create_foreign_key(None, 'animal', 'animal', ['parent_id'], ['animal_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animal', type_='foreignkey')
    op.create_foreign_key('animal_parent_id_fkey', 'animal', 'animal', ['parent_id'], ['animal_id'])
    # ### end Alembic commands ###
