"""add unique constraint on breed type_id and name

Revision ID: fcaffdfdaf86
Revises: 73b035168c71
Create Date: 2026-07-26 19:37:00.296605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaffdfdaf86'
down_revision: Union[str, Sequence[str], None] = '73b035168c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_breed_type_name', 'breed', ['type_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_breed_type_name', 'breed', type_='unique')
    # ### end Alembic commands ###
